pub mod bench_baseline;
pub mod chunker;
pub mod classifier;
pub mod cli;
pub mod cli_args_logic;
pub mod cli_dict_logic;
pub mod cli_format;
pub mod cli_rebuild_logic;
pub mod config;
mod config_accessors;
pub mod daemon;
pub mod daemon_lock;
pub mod daemon_protocol;
pub mod db;
pub mod doc_links;
pub mod embedder;
pub mod entity;
pub mod frontmatter;
pub mod indexer;
pub mod ipc;
pub mod logging;
pub mod lua_hooks;
pub mod manifest;
pub mod model_loader;
pub mod paths;
pub mod placement;
pub mod read_pool;
pub mod render;
pub mod searcher;
pub mod session_chunker;
pub mod status;
pub mod synonyms;
pub mod temporal;
pub mod tokenizer;
pub mod user_dict;

#[cfg(test)]
pub mod test_utils;
