name: DevContainer

on:
  push:
    branches: [main]
    paths:
      - ".devcontainer/**"
  pull_request:
    paths:
      - ".devcontainer/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Create dummy .env
        run: touch .env
      - name: Build DevContainer
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca  # v0.3
        with:
          runCmd: |
            rumdl --version
            ryl --version
            shellcheck --version
            taplo --version
            gh --version
            jq --version
            cargo --version
