name: DevContainer

on:
  push:
    branches: [main]
    paths:
      - ".devcontainer/**"
  pull_request:
    paths:
      - ".devcontainer/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Create dummy .env
        run: touch .env
      - name: Build DevContainer
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5  # v0.3
        with:
          runCmd: |
            rumdl --version
            yamllint --version
            shellcheck --version
            taplo --version
            gh --version
            jq --version
            cargo --version
